"""add new column public_id  into User tabel

Revision ID: 336e3def1031
Revises: 7b6625fd3c9a
Create Date: 2026-10-05 20:46:05.197804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '336e3def1031'
down_revision: Union[str, Sequence[str], None] = '7b6625fd3c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.Uuid(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
