"""change foreign key in nba_players table

Revision ID: 40bfeaf221cf
Revises: 94bb088a1496
Create Date: 2026-09-22 21:11:40.507177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bfeaf221cf'
down_revision: Union[str, Sequence[str], None] = '94bb088a1496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('nba_players_player_team_fkey'), 'nba_players', type_='foreignkey')
    op.create_foreign_key(None, 'nba_players', 'nba_teams', ['player_team'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'nba_players', type_='foreignkey')
    op.create_foreign_key(op.f('nba_players_player_team_fkey'), 'nba_players', 'nba_teams', ['player_team'], ['id'])
    # ### end Alembic commands ###
