"""Change foreign key in column team_id in user favorite teams table

Revision ID: 7b6625fd3c9a
Revises: caebe8722363
Create Date: 2026-09-29 15:46:04.267645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6625fd3c9a'
down_revision: Union[str, Sequence[str], None] = 'caebe8722363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_favorite_teams_team_id_fkey'), 'user_favorite_teams', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorite_teams', 'nba_teams', ['team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_favorite_teams', type_='foreignkey')
    op.create_foreign_key(op.f('user_favorite_teams_team_id_fkey'), 'user_favorite_teams', 'nba_teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
