"""Add new column is_active into nba_players table

Revision ID: 94bb088a1496
Revises: e1c4e163f3ce
Create Date: 2026-09-18 23:12:51.477771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bb088a1496'
down_revision: Union[str, Sequence[str], None] = 'e1c4e163f3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nba_players",sa.Column("is_active", sa.Boolean(), nullable = False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("nba_players", "is_active")
    # ### end Alembic commands ###

