"""inicjalizacja_bazy_nba

Revision ID: b00597db2665
Revises: 
Create Date: 2026-09-18 01:19:28.347423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00597db2665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nba_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_index(op.f('ix_nba_teams_id'), 'nba_teams', ['id'], unique=False)
    op.create_table('status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_description', sa.String(), nullable=False),
    sa.Column('downloaded_records', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('log_type', sa.Enum('players_log', 'teams_log', 'teams_list', 'players_list', name='log_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_log_id'), 'status_log', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='enum_name'), nullable=False),
    sa.Column('user_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('nba_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_last_name', sa.String(), nullable=False),
    sa.Column('player_team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_team'], ['nba_teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_nba_players_id'), 'nba_players', ['id'], unique=False)
    op.create_table('teams_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('field_goal_percentage', sa.Float(), nullable=False),
    sa.Column('three_point_field_goals_made', sa.Integer(), nullable=False),
    sa.Column('three_point_field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('three_point_field_goal_percentage', sa.Float(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throw_percentage', sa.Float(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('blocks_against', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.Column('personal_fouls_drawn', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_game_logs_id'), 'teams_game_logs', ['id'], unique=False)
    op.create_table('user_favorite_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_teams_id'), 'user_favorite_teams', ['id'], unique=False)
    op.create_table('players_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.Float(), nullable=False),
    sa.Column('field_goals_made', sa.Integer(), nullable=False),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('field_goal_percentage', sa.Float(), nullable=False),
    sa.Column('three_point_field_goals_made', sa.Integer(), nullable=False),
    sa.Column('three_point_field_goals_attempted', sa.Integer(), nullable=False),
    sa.Column('three_point_field_goal_percentage', sa.Float(), nullable=False),
    sa.Column('free_throws_made', sa.Integer(), nullable=False),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=False),
    sa.Column('free_throw_percentage', sa.Float(), nullable=False),
    sa.Column('offensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('defensive_rebounds', sa.Integer(), nullable=False),
    sa.Column('rebounds', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.Column('steals', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('blocks_against', sa.Integer(), nullable=False),
    sa.Column('personal_fouls', sa.Integer(), nullable=False),
    sa.Column('personal_fouls_drawn', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['nba_teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_game_logs_id'), 'players_game_logs', ['id'], unique=False)
    op.create_table('user_favorite_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['nba_players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorite_player_id'), 'user_favorite_player', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_player_id'), table_name='user_favorite_player')
    op.drop_table('user_favorite_player')
    op.drop_index(op.f('ix_players_game_logs_id'), table_name='players_game_logs')
    op.drop_table('players_game_logs')
    op.drop_index(op.f('ix_user_favorite_teams_id'), table_name='user_favorite_teams')
    op.drop_table('user_favorite_teams')
    op.drop_index(op.f('ix_teams_game_logs_id'), table_name='teams_game_logs')
    op.drop_table('teams_game_logs')
    op.drop_index(op.f('ix_nba_players_id'), table_name='nba_players')
    op.drop_table('nba_players')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_status_log_id'), table_name='status_log')
    op.drop_table('status_log')
    op.drop_index(op.f('ix_nba_teams_id'), table_name='nba_teams')
    op.drop_table('nba_teams')
    # ### end Alembic commands ###
