"""Change ForeignKey in user_favorite_players table in column player_id

Revision ID: caebe8722363
Revises: f9f6500fbdcb
Create Date: 2026-09-29 03:05:31.648483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caebe8722363'
down_revision: Union[str, Sequence[str], None] = 'f9f6500fbdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nba_players', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('user_favorite_player_player_id_fkey'), 'user_favorite_player', type_='foreignkey')
    op.create_foreign_key(None, 'user_favorite_player', 'nba_players', ['player_id'], ['player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'user_favorite_player', type_='foreignkey')
    op.create_foreign_key(op.f('user_favorite_player_player_id_fkey'), 'user_favorite_player', 'nba_players', ['player_id'], ['id'])
    op.alter_column('nba_players', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
