"""Add new column into teams_game_logs table

Revision ID: e1c4e163f3ce
Revises: b00597db2665
Create Date: 2026-09-18 16:11:29.818704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c4e163f3ce'
down_revision: Union[str, Sequence[str], None] = 'b00597db2665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams_game_logs",sa.Column("season", sa.String(), nullable = False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("teams_game_logs", "season")
    # ### end Alembic commands ###
