"""Add column display_name into Players table

Revision ID: f9f6500fbdcb
Revises: 40bfeaf221cf
Create Date: 2026-09-29 00:15:23.529792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f6500fbdcb'
down_revision: Union[str, Sequence[str], None] = '40bfeaf221cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nba_players', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nba_players', 'display_name')
    # ### end Alembic commands ###
